SELECT 
	 A.ID_ACESSO AS ID
    ,A.DESCRICAO
    ,A.DATA_CRIACAO DATACRIACAO
FROM ACESSOS_SISTEMICOS A
WHERE
	A.DESCRICAO LIKE CONCAT('%',@DESCRICAO,'%')

SELECT 
	 A.ID_ACESSO AS ACESSO
	,P.ID_PERMISSAO AS ID
	,P.PERMISSAO
	,P.DESCRICAO
	,P.DATA_CRIACAO DATACRIACAO
FROM ACESSOS_SISTEMICOS A
INNER JOIN ACESSOS_SISTEMICOS_PERMISSOES AP ON
	A.ID_ACESSO = AP.ACESSO
INNER JOIN PERMISSOES P ON
	AP.PERMISSAO = P.ID_PERMISSAO
WHERE
	A.DESCRICAO LIKE CONCAT('%',@DESCRICAO,'%')