SELECT 
	 A.ID_ACESSO AS ID
    ,A.DESCRICAO
    ,A.DATA_CRIACAO DATACRIACAO
FROM ACESSOS_SISTEMICOS A
LEFT JOIN ACESSOS_SISTEMICOS_GRUPOS G ON
	A.ID_ACESSO = G.ACESSO 
LEFT JOIN ACESSOS_SISTEMICOS_USUARIOS U ON
	A.ID_ACESSO = U.ACESSO
LEFT JOIN USUARIOS US ON
	U.USUARIO = US.ID_USUARIO
WHERE
	U.USUARIO = @USUARIO

SELECT 
	 A.ID_ACESSO AS ACESSO
	,P.ID_PERMISSAO AS ID
	,P.PERMISSAO
	,P.DESCRICAO
	,P.DATA_CRIACAO DATACRIACAO
FROM ACESSOS_SISTEMICOS A
LEFT JOIN ACESSOS_SISTEMICOS_GRUPOS G ON
	A.ID_ACESSO = G.ACESSO 
LEFT JOIN ACESSOS_SISTEMICOS_USUARIOS U ON
	A.ID_ACESSO = U.ACESSO
LEFT JOIN USUARIOS US ON
	U.USUARIO = US.ID_USUARIO
WHERE
	U.USUARIO = @USUARIO
