IF EXISTS (SELECT 1 FROM PERMISSOES_GRUPOS WHERE GRUPO = @GRUPO AND PERMISSAO = @PERMISSAO)
    THROW 51000, 'Permissão cadastrada já existe', 1;  

INSERT INTO PERMISSOES_GRUPOS (GRUPO, PERMISSAO, DATA_CRIACAO, USUARIO_RESPONSAVEL)
VALUES							(@GRUPO, @PERMISSAO, GETDATE(), 1)