IF EXISTS (SELECT 1 FROM PERMISSOES_USUARIOS WHERE USUARIO = @USUARIO AND PERMISSAO = @PERMISSAO)
    THROW 51000, 'Permissão cadastrada já existe', 1;  

INSERT INTO PERMISSOES_USUARIOS (USUARIO, PERMISSAO, DATA_CRIACAO, USUARIO_RESPONSAVEL)
VALUES							(@USUARIO, @PERMISSAO, GETDATE(), 1)