IF EXISTS (SELECT 1 FROM ACESSOS_SISTEMICOS WHERE DESCRICAO = @DESCRICAO)
    THROW 51000, 'Acesso Sistêmico informado já existe', 1;  
    
INSERT INTO ACESSOS_SISTEMICOS VALUES (@DESCRICAO, GETDATE(), 1, 1)