IF NOT EXISTS (SELECT 1 FROM PERMISSOES WHERE ID_PERMISSAO = @PERMISSAO)
    THROW 51000, 'Permissão não encontrada. Verifique os dados.', 1;  

IF NOT EXISTS (SELECT 1 FROM GRUPOS WHERE ID_GRUPO = @GRUPO)
    THROW 51000, 'Grupo não encontrado. Verifique os dados.', 1;  

IF EXISTS (SELECT 1 FROM PERMISSOES_GRUPOS WHERE GRUPO = @GRUPO AND PERMISSAO = @PERMISSAO)
    THROW 51000, 'Permissão para grupo já existe', 1;  

INSERT INTO PERMISSOES_GRUPOS (GRUPO, PERMISSAO, DATA_CRIACAO, USUARIO_RESPONSAVEL)
VALUES							(@GRUPO, @PERMISSAO, GETDATE(), 1)