SELECT DISTINCT
    P.ID_PERMISSAO AS ID,
    P.PERMISSAO,
    P.NOME,
    P.DESCRICAO,
    P.ATIVO
FROM PERMISSOES P
LEFT JOIN PERMISSOES_USUARIOS PU ON
	PU.PERMISSAO = P.ID_PERMISSAO
LEFT JOIN PERMISSOES_GRUPOS PG ON
	PG.PERMISSAO = P.ID_PERMISSAO
WHERE 
(	
	PU.USUARIO = @USUARIO
	OR	PG.GRUPO = (SELECT GRUPO FROM USUARIOS WHERE ID_USUARIO = @USUARIO)
)
AND P.ATIVO = 1