SELECT DISTINCT
    P.ID_PERMISSAO AS ID,
    P.PERMISSAO,
    P.NOME,
    P.DESCRICAO,
    P.ATIVO
FROM PERMISSOES P
INNER JOIN PERMISSOES_GRUPOS G ON
	P.ID_PERMISSAO = G.PERMISSAO
WHERE
	G.GRUPO = @GRUPO
AND P.ATIVO = 1