SELECT
	A.ID_ACESSO ID
,	A.DESCRICAO DESCRICAO
,	A.ATIVO ATIVO
,	P.ID_PERMISSAO PERMISSOES_ID
,	P.PERMISSAO PERMISSOES_PERMISSAO
,	P.DESCRICAO	PERMISSOES_DESCRICAO
FROM ACESSOS_SISTEMICOS A
INNER JOIN ACESSOS_SISTEMICOS_PERMISSOES AP ON
	A.ID_ACESSO = AP.ACESSO
INNER JOIN PERMISSOES P ON
	P.ID_PERMISSAO = AP.PERMISSAO
INNER JOIN ACESSOS_SISTEMICOS_GRUPOS AG ON
	AG.ACESSO = A.ID_ACESSO
INNER JOIN GRUPOS G ON
	G.ID_GRUPO = AG.GRUPO
WHERE
	G.ID_GRUPO = @GRUPO
AND A.ATIVO = 1