SELECT
	A.ID_ACESSO ID
,	A.DESCRICAO DESCRICAO
,	A.ATIVO ATIVO
,	P.ID_PERMISSAO PERMISSOES_ID
,	P.PERMISSAO PERMISSOES_PERMISSAO
,	P.DESCRICAO	PERMISSOES_DESCRICAO
FROM ACESSOS_SISTEMICOS A
INNER JOIN ACESSOS_SISTEMICOS_PERMISSOES AP ON
	A.ID_ACESSO = AP.ACESSO
INNER JOIN PERMISSOES P ON
	P.ID_PERMISSAO = AP.PERMISSAO
INNER JOIN ACESSOS_SISTEMICOS_USUARIOS AU ON
	AU.ACESSO = A.ID_ACESSO
LEFT JOIN ACESSOS_SISTEMICOS_GRUPOS AG ON
	AG.ACESSO = A.ID_ACESSO
INNER JOIN USUARIOS U ON
	U.ID_USUARIO = AU.USUARIO
OR	U.GRUPO = AG.GRUPO
WHERE
	U.ID_USUARIO = @USUARIO
AND A.ATIVO = 1