IF EXISTS (SELECT 1 FROM USUARIOS WHERE USUARIO = @USUARIO)
     THROW 51000, 'Usuário Já foi cadastrado.', 1;  

INSERT INTO USUARIOS 
(
     USUARIO
    ,SENHA
    ,DATA_CRIACAO
    ,DATA_CADASTRO_SENHA
    ,DIAS_RENOVACAO
    ,ATIVO
    ,GRUPO
    ,PESSOA
)
VALUES
(
     @USUARIO
    ,@SENHA
    ,@DATACRIACAO
    ,@DATACADASTROSENHA
    ,@DIASRENOVACAO
    ,@ATIVO
    ,@IDGRUPO
    ,@IDPESSOA
)

