SELECT 
     ID_USUARIO AS ID
    ,USUARIO
    ,'' AS SENHA
    ,DATA_CRIACAO AS DATACRIACAO
    ,DATA_CADASTRO_SENHA AS DATACADASTROSENHA
    ,DIAS_RENOVACAO AS DIASRENOVACAO
    ,ATIVO
    ,GRUPO AS IDGRUPO
    ,PESSOA AS IDPESSOA
FROM USUARIOS
WHERE ID_USUARIO = @USUARIO

SELECT
     ID_GRUPO AS ID
    ,NOME
    ,DESCRICAO
    ,ID_PAI AS PAI
FROM USUARIOS U
INNER JOIN GRUPOS G ON
    U.GRUPO = G.ID_GRUPO
WHERE U.ID_USUARIO = @USUARIO

SELECT 
     P.ID_PESSOA AS ID
    ,P.NOME
    ,P.CPF
    ,P.EMAIL
    ,P.DDD
    ,P.NUMERO
FROM USUARIOS U
INNER JOIN PESSOAS P ON
    U.PESSOA = P.ID_PESSOA
WHERE U.ID_USUARIO = @USUARIO