IF EXISTS(SELECT 1 FROM GRUPOS WHERE NOME = @NOME)
    THROW 51000, 'Grupo informado já existe.', 1;  

DECLARE @IDPAI_CAST INT = NULL

IF @ID_PAI > 0
	SET @IDPAI_CAST = @ID_PAI

INSERT INTO GRUPOS VALUES (@NOME, @DESCRICAO, @IDPAI_CAST)