DECLARE
    @CPFFORNECIDO CHAR(11)

SET @CPFFORNECIDO = IIF(@CPF = 0,NULL, @CPF)

IF @CPFFORNECIDO IS NULL
    INSERT INTO PESSOAS VALUES (@NOME, @CPFFORNECIDO, @EMAIL, @DDD, @NUMERO)
ELSE IF NOT EXISTS(SELECT 1 FROM PESSOAS WHERE CPF = @CPF)
    INSERT INTO PESSOAS VALUES (@NOME, @CPFFORNECIDO, @EMAIL, @DDD, @NUMERO)