IF @JUSTIFICATIVA IS NULL AND @NIVEL > 1
BEGIN
	IF EXISTS(SELECT 1 FROM GRUPOS WHERE ID_GRUPO = @ID)
	UPDATE GRUPOS
	SET NIVEL = @NIVEL
	WHERE ID_GRUPO = @ID
END
ELSE
BEGIN
	IF EXISTS(SELECT 1 FROM GRUPOS WHERE ID_GRUPO = @ID)
	UPDATE GRUPOS
	SET NIVEL = @NIVEL
	,	JUSTIFICATIVA = @JUSTIFICATIVA
	WHERE ID_GRUPO = @ID
END