//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servico.Recurso {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensagensErro {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensagensErro() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Servico.Recurso.MensagensErro", typeof(MensagensErro).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu uma falha ao cadastrar este grupo. Tente novamente mais tarde..
        /// </summary>
        public static string GrupoFalhaCadastro {
            get {
                return ResourceManager.GetString("GrupoFalhaCadastro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu uma falha ao realizar o vínculo, tente novamente mais tarde..
        /// </summary>
        public static string GrupoFalhaVinculo {
            get {
                return ResourceManager.GetString("GrupoFalhaVinculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível localizar o grupo. Verifique os dados e tente novamente..
        /// </summary>
        public static string GrupoNaoLocalizado {
            get {
                return ResourceManager.GetString("GrupoNaoLocalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pai informado para o novo grupo inválido..
        /// </summary>
        public static string GrupoPaiInvalido {
            get {
                return ResourceManager.GetString("GrupoPaiInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Grupo foi excluído com sucesso!.
        /// </summary>
        public static string GrupoSucessoExclusao {
            get {
                return ResourceManager.GetString("GrupoSucessoExclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Grupo adicionado com sucesso!.
        /// </summary>
        public static string GrupoSucessoInclusao {
            get {
                return ResourceManager.GetString("GrupoSucessoInclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Grupos foram vinculados com sucesso!.
        /// </summary>
        public static string GrupoSucessoVinculo {
            get {
                return ResourceManager.GetString("GrupoSucessoVinculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível alterar a atividade da permissão, verifique os dados e tente novamente mais tarde.
        /// </summary>
        public static string PermissaoFalhaAtualizar {
            get {
                return ResourceManager.GetString("PermissaoFalhaAtualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível excluir permissão indicada, verifique os dados e tente novamente mais tarde.
        /// </summary>
        public static string PermissaoFalhaExclusao {
            get {
                return ResourceManager.GetString("PermissaoFalhaExclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao adicionar permissão, verifique os dados e tente novamente..
        /// </summary>
        public static string PermissaoFalhaInclusao {
            get {
                return ResourceManager.GetString("PermissaoFalhaInclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível encontrar a permissão com Identificador N.
        /// </summary>
        public static string PermissaoNaoEncontrada {
            get {
                return ResourceManager.GetString("PermissaoNaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Permissão alterada com sucesso!.
        /// </summary>
        public static string PermissaoSucessoAtualizar {
            get {
                return ResourceManager.GetString("PermissaoSucessoAtualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Permissão excluída com sucesso!.
        /// </summary>
        public static string PermissaoSucessoExclusao {
            get {
                return ResourceManager.GetString("PermissaoSucessoExclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Permissão adicionada com sucesso!.
        /// </summary>
        public static string PermissaoSucessoInclusao {
            get {
                return ResourceManager.GetString("PermissaoSucessoInclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível cadastrar a permissão, verifique os dados e tente novamente mais tarde.
        /// </summary>
        public static string PermissaoTerceirosFalhaInclusao {
            get {
                return ResourceManager.GetString("PermissaoTerceirosFalhaInclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A consulta não retornou resultados..
        /// </summary>
        public static string PesquisaSemResultados {
            get {
                return ResourceManager.GetString("PesquisaSemResultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível localizar a pessoa indicada para alteração de dados..
        /// </summary>
        public static string PessoaAlteracaoNaoEncontrada {
            get {
                return ResourceManager.GetString("PessoaAlteracaoNaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Para realizar a alteração da pessoa, ao menos um dado deve ser solicitado..
        /// </summary>
        public static string PessoaAlteracaoSemDados {
            get {
                return ResourceManager.GetString("PessoaAlteracaoSemDados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Para realizar a alteração da pessoa, deve ser informado o número de identificação da mesma..
        /// </summary>
        public static string PessoaAlteracaoSemId {
            get {
                return ResourceManager.GetString("PessoaAlteracaoSemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dados da pessoa atualizados com sucesso!.
        /// </summary>
        public static string PessoaAlteracaoSucesso {
            get {
                return ResourceManager.GetString("PessoaAlteracaoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível atualizar a pessoa. Favor Verificar os dados..
        /// </summary>
        public static string PessoaFalhaAlteracao {
            get {
                return ResourceManager.GetString("PessoaFalhaAlteracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível deletar a pessoa. Tente novamente mais tarde..
        /// </summary>
        public static string PessoaFalhaExclusao {
            get {
                return ResourceManager.GetString("PessoaFalhaExclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível incluir esta pessoa. Verifique os dados ou tente novamente mais tarde..
        /// </summary>
        public static string PessoaFalhaInclusao {
            get {
                return ResourceManager.GetString("PessoaFalhaInclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pessoa foi excluída com sucesso!.
        /// </summary>
        public static string PessoaSucessoExclusao {
            get {
                return ResourceManager.GetString("PessoaSucessoExclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pessoa adicionada com sucesso!.
        /// </summary>
        public static string PessoaSucessoInclusao {
            get {
                return ResourceManager.GetString("PessoaSucessoInclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Houve erros de validação. Favor verificar notificações..
        /// </summary>
        public static string RegraNegocioErroValidacao {
            get {
                return ResourceManager.GetString("RegraNegocioErroValidacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuario está bloqueado.
        /// </summary>
        public static string UsuarioBloqueado {
            get {
                return ResourceManager.GetString("UsuarioBloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha e confirmação de senha não são iguais, verifique os dados..
        /// </summary>
        public static string UsuarioFalhaConfirmacaoSenha {
            get {
                return ResourceManager.GetString("UsuarioFalhaConfirmacaoSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível adicionar o novo usuário. Tente novamente mais tarde..
        /// </summary>
        public static string UsuarioFalhaInclusao {
            get {
                return ResourceManager.GetString("UsuarioFalhaInclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível localizar o grupo do usuário informado, contate o suporte técnico para mais informações..
        /// </summary>
        public static string UsuarioGrupoInvalido {
            get {
                return ResourceManager.GetString("UsuarioGrupoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Grupo do usuário não encontrado..
        /// </summary>
        public static string UsuarioGrupoNaoEncontrado {
            get {
                return ResourceManager.GetString("UsuarioGrupoNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível localizar o usuário. Verifique os dados e tente novamente..
        /// </summary>
        public static string UsuarioNaoLocalizado {
            get {
                return ResourceManager.GetString("UsuarioNaoLocalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pessoa do usuário não encontrada..
        /// </summary>
        public static string UsuarioPessoaNaoEncontrada {
            get {
                return ResourceManager.GetString("UsuarioPessoaNaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha do usuário informado está expirada..
        /// </summary>
        public static string UsuarioSenhaExpirada {
            get {
                return ResourceManager.GetString("UsuarioSenhaExpirada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário foi atualizado com sucesso!.
        /// </summary>
        public static string UsuarioSucessoAtualizacao {
            get {
                return ResourceManager.GetString("UsuarioSucessoAtualizacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário foi excluído com sucesso!.
        /// </summary>
        public static string UsuarioSucessoExclusao {
            get {
                return ResourceManager.GetString("UsuarioSucessoExclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário Adicionado com sucesso!.
        /// </summary>
        public static string UsuarioSucessoInclusao {
            get {
                return ResourceManager.GetString("UsuarioSucessoInclusao", resourceCulture);
            }
        }
    }
}
