//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidade.Recurso {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Entidade.Recurso.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Descrição do grupo deve conter menos de N caractéres..
        /// </summary>
        internal static string GrupoDescricaoMaximo {
            get {
                return ResourceManager.GetString("GrupoDescricaoMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Descrição do grupo deve conter mais de N caractéres..
        /// </summary>
        internal static string GrupoDescricaoMinimo {
            get {
                return ResourceManager.GetString("GrupoDescricaoMinimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome do grupo deve ter menos de N caractéres..
        /// </summary>
        internal static string GrupoNomeMaximo {
            get {
                return ResourceManager.GetString("GrupoNomeMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome do grupo deve ter mais de N caractéres..
        /// </summary>
        internal static string GrupoNomeMinimo {
            get {
                return ResourceManager.GetString("GrupoNomeMinimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome do grupo não pode conter números..
        /// </summary>
        internal static string GrupoNomeNumeros {
            get {
                return ResourceManager.GetString("GrupoNomeNumeros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível sobrescrever a mensageria do objeto..
        /// </summary>
        internal static string MensageriaErroSobrescrita {
            get {
                return ResourceManager.GetString("MensageriaErroSobrescrita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome é obrigatório..
        /// </summary>
        internal static string NomeObrigatorio {
            get {
                return ResourceManager.GetString("NomeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF inválido, verifique os dados..
        /// </summary>
        internal static string PessoaCPFInvalido {
            get {
                return ResourceManager.GetString("PessoaCPFInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ao menos uma forma de contato deve ser fornecido da pessoa..
        /// </summary>
        internal static string PessoaFormaContato {
            get {
                return ResourceManager.GetString("PessoaFormaContato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome e sobrenomes dos usuários devem iniciar com letra maiúscula..
        /// </summary>
        internal static string PessoaNomeMaiusculo {
            get {
                return ResourceManager.GetString("PessoaNomeMaiusculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Número de telefone inválido..
        /// </summary>
        internal static string PessoaNumeroInvalido {
            get {
                return ResourceManager.GetString("PessoaNumeroInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Telefone da pessoa deve conter DDD..
        /// </summary>
        internal static string PessoaTelefoneInvalido {
            get {
                return ResourceManager.GetString("PessoaTelefoneInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário deve iniciar com letra maiúscula..
        /// </summary>
        internal static string UsuarioLetraMaiuscula {
            get {
                return ResourceManager.GetString("UsuarioLetraMaiuscula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário deve conter mais de N caractéres..
        /// </summary>
        internal static string UsuarioMinimo {
            get {
                return ResourceManager.GetString("UsuarioMinimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário é obrigatório..
        /// </summary>
        internal static string UsuarioObrigatorio {
            get {
                return ResourceManager.GetString("UsuarioObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha do usuário deve conter ao menos uma letra maiúscula, um número e um caractere especial.
        /// </summary>
        internal static string UsuarioSenhaEspecificacoes {
            get {
                return ResourceManager.GetString("UsuarioSenhaEspecificacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha deve conter mais de N caractéres.
        /// </summary>
        internal static string UsuarioSenhaMinima {
            get {
                return ResourceManager.GetString("UsuarioSenhaMinima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha do usuário é obrigatória..
        /// </summary>
        internal static string UsuarioSenhaObrigatoria {
            get {
                return ResourceManager.GetString("UsuarioSenhaObrigatoria", resourceCulture);
            }
        }
    }
}
