IF @JUSTIFICATIVA IS NULL AND @NIVEL > 1
BEGIN
	IF EXISTS(SELECT 1 FROM GRUPOS WHERE NOME = @NOME)
	UPDATE GRUPOS
	SET NIVEL = @NIVEL
	WHERE NOME = @NOME
END
ELSE
BEGIN
	IF EXISTS(SELECT 1 FROM GRUPOS WHERE NOME = @NOME)
	UPDATE GRUPOS
	SET NIVEL = @NIVEL
	,	JUSTIFICATIVA = @JUSTIFICATIVA
	WHERE NOME = @NOME
END