CREATE TABLE GRUPOS(
	ID_GRUPO	INT IDENTITY,
	NOME		VARCHAR(80) NOT NULL,
	DESCRICAO	VARCHAR(200),
	NIVEL		INT NOT NULL,
	JUSTIFICATIVA VARCHAR(500)
)

ALTER TABLE GRUPOS ADD
	CONSTRAINT [PK_ID_GRUPO] PRIMARY KEY (ID_GRUPO),
	CONSTRAINT [UNIQUE_GRUPOS_NOME] UNIQUE NONCLUSTERED (NOME);

CREATE INDEX DADOS_GERAIS_GRUPO ON GRUPOS (NOME, DESCRICAO, NIVEL);
CREATE INDEX DADOS_NIVEL_GRUPO ON GRUPOS (NOME, NIVEL, JUSTIFICATIVA);