DECLARE
    @CPFFORNECIDO CHAR(11),
    @TELEFONEFORNECIDO VARCHAR(11)

SET @CPFFORNECIDO = IIF(@CPF = 0,NULL, @CPF)
SET @TELEFONEFORNECIDO = IIF(@TELEFONE = 0,NULL, @TELEFONE)

IF @CPFFORNECIDO IS NULL
    INSERT INTO PESSOAS VALUES (@NOME, @CPFFORNECIDO, @EMAIL, @TELEFONEFORNECIDO)
ELSE IF NOT EXISTS(SELECT 1 FROM PESSOAS WHERE CPF = @CPF)
    INSERT INTO PESSOAS VALUES (@NOME, @CPFFORNECIDO, @EMAIL, @TELEFONEFORNECIDO)